import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutWithNavbar from "./LayoutWithNavbar"; // ← impor komponen client

// Load font secara aman untuk SSR
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "E-Shop",
  description: "Generated by create E-Shop",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* LayoutWithNavbar akan mengatur Navbar otomatis */}
        <LayoutWithNavbar>{children}</LayoutWithNavbar>
      </body>
    </html>
  );
}
